### ISSUE TITLE
[Enhancement] Contribution Guide link in Knowledge Base

### ISSUE THREAD

**Issue by andreaschrader** [Freymaurer/nfdi4plants-fornax-template#14]
This issue (https://github.com/nfdi4plants/nfdi4plants.knowledgebase/issues/44) was hanging from work at a Hackathon on the DataPLANT Knowledge Base Contributon Guide and seems to require Fornax. I think this needs to be done here in order to have this on all pages of the Knowledge Base?

As I am not experienced in Fornax, I made a suggestion below but kindly ask you to check my suggestion and to implement it correctly.

The idea was to place the Contribution Guide more prominently. 

There could be a link on the left side and next or just above and left of the "Edit this page" link directly showing the way to the contribution guide.

**Suggestion:**

I think, the following could do this when placed before line 47 in the file mentioned below. This is just derived from the "Edit this page" link chunck in line 47 and following in Nfdi4Plants.Fornax/src/Nfdi4Plants.Fornax/Components.fs

```
            // Contribution Guide link
            // https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/CONTRIBUTING.html
            div [] [
                a [
                    Target "_blank"
                    Href "https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/CONTRIBUTING.html"; 
                    HtmlProperties.Style [MarginRight "auto"; Display "block"; CSSProperties.Width "130px"]
                ] [!! "✏️ Contribution Guide"]
            ]
```

**Comment by Freymaurer** [comment]
Will look into this tomorrow. Should i not answer here tomorrow feel free to contact me on teams or ping me here again 😄

**Comment by Freymaurer** [comment]
Done! 
![image](https://github.com/nfdi4plants/Nfdi4Plants.Fornax/assets/39732517/a4d8dede-3133-4d14-b8f9-a3f6c470bc14)

Will be updated next Thursday evening
