### ISSUE TITLE
[feature] search bar

### ISSUE THREAD

**Issue by Brilator** [Freymaurer/nfdi4plants-fornax-template#8]
Would be cool to have a search function / search bar for the knowledge base, docs, etc.

**Comment by Freymaurer** [comment]
Rest will need to be done in fornax repo

**Comment by Freymaurer** [comment]
![image](https://github.com/nfdi4plants/Nfdi4Plants.Fornax/assets/39732517/48f51dc7-eae7-4133-997e-a6bbc434e1d5)
